---
- name: Check if cluster has to be enabled and cluster_name is defined
  assert:
    that:
      - rabbitmq_clustering_enabled
      - rabbitmq_clustering_cluster_name | default('', true) | length > 4
    fail_msg: "When using cluster a cluster_name must be set with at least 5 chars"
  run_once: true

- name: Set dynamic group name
  set_fact:
    cluster_group_name: "rmq_cluster_{{ rabbitmq_clustering_cluster_name }}"
  run_once: true

- name: Set dynamic group based on cluster_name
  group_by:
    key: "{{ cluster_group_name }}"
  delegate_to: localhost

- name: Show the name of master node
  debug:
    msg: "{{ groups[cluster_group_name][0] }}"
    verbosity: 2
  run_once: true

- name: Check RabbitMQ is running in cluster mode
  command: rabbitmqctl cluster_status --formatter json
  delegate_to: "{{ groups[cluster_group_name][0] }}"
  run_once: true
  changed_when: false
  register: rabbitmq_cluster_status

- name: Set rabbitmq_cluster_running_nodes fact
  set_fact:
    rabbitmq_cluster_status: "{{ rabbitmq_cluster_status.stdout | from_json }}"
  run_once: true

- name: Task block to clear new nodes before joining to cluster
  block:
    - name: Stop rabbitmq app
      command: rabbitmqctl stop_app

    - name: Reset rabbitmq before entering cluster
      command: rabbitmqctl force_reset

    - name: Force forget cluster node on 'master'
      command: "rabbitmqctl forget_cluster_node {{ rabbitmq_node }}"
      delegate_to: "{{ groups[cluster_group_name][0] }}"
      when:
        - (rabbitmq_node in rabbitmq_cluster_status['running_nodes'])

    - name: Waiting for a while to nodes stabilize themselves
      wait_for:
        timeout: 15

    - name: Join rabbitmq cluster
      command: rabbitmqctl join_cluster "rabbit@{{ groups[cluster_group_name][0] }}"
      register: cluster_joined
      retries: 3
      delay: 15

    - name: Start rabbitmq app
      command: rabbitmqctl start_app
  vars:
    rabbitmq_node: "rabbit@{{ inventory_hostname }}"
  when:
    - inventory_hostname != groups[cluster_group_name][0]
    - (rabbitmq_node not in rabbitmq_cluster_status['running_nodes']) or (rabbitmq_clustering_force)

- name: Set rabbitmq cluster name
  rabbitmq_global_parameter:
    name: cluster_name
    value: "{{ rabbitmq_clustering_cluster_name | to_json }}"
    state: present
