---
- name: Manage Exchanges
  rabbitmq_exchange:
    login_user: "{{ exchange_item.login_user | default(rabbitmq_api_login_credentials['login_user'] | default(omit)) }}"
    login_password: "{{ exchange_item.login_password | default(rabbitmq_api_login_credentials['login_password'] | default(omit)) }}"
    login_host: "{{ exchange_item.login_host | default(rabbitmq_api_login_credentials['login_host'] | default(omit)) }}"
    login_port: "{{ exchange_item.login_port | default(rabbitmq_api_login_credentials['login_port'] | default(omit)) }}"
    login_protocol: "{{ exchange_item.login_protocol | default(rabbitmq_api_login_credentials['login_protocol'] | default(omit) }}"
    ca_cert: "{{ exchange_item.ca_cert | default(rabbitmq_api_login_credentials['ca_cert'] | default(omit)) }}"
    client_cert: "{{ exchange_item.client_cert | default(rabbitmq_api_login_credentials['client_cert'] | default(omit)) }}"
    client_key: "{{ exchange_item.client_key | default(rabbitmq_api_login_credentials['client_key'] | default(omit)) }}"
    vhost: "{{ exchange_item.value.vhost | default(omit) }}"
    name: "{{ exchange_item.key }}"
    type: "{{ exchange_item.value.type | default(omit) }}"
    arguments: "{{ exchange_item.value.arguments | default(omit) }}"
    auto_delete: "{{ exchange_item.value.auto_delete | default(omit) }}"
    durable: "{{ exchange_item.value.durable | default(omit) }}"
    internal: "{{ exchange_item.value.internal | default(omit) }}"
    state: "{{ exchange_item.value.state | default(omit) }}"