---
- name: Get RabbitMQ installed plugins
  command: rabbitmq-plugins list -e -m
  changed_when: false
  register: rabbitmq_installed_plugins

- name: Enable plugins
  rabbitmq_plugin:
    names: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ rabbitmq_plugins }}"
  when:
    - rabbitmq_plugins | length > 0
    - item.name not in rabbitmq_installed_plugins.stdout_lines

- name: Force to correct enabled plugins permissions
  file:
    path: "{{ rabbitmq_enabled_plugins_file_path }}"
    owner: "{{ rabbitmq_owner }}"
    group: "{{ rabbitmq_group }}"
    mode: "0644"
